spring:
  data:
    redis:
      host: 43.143.220.198
      port: 8000
      database: 0
      password: redis@123
      timeout: 10s
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.143.220.198:8001/workstation?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root@123
  flyway:
    enabled: true
    locations: classpath:db/migration
    table: flyway_schema_history
