# 设置端口
server:
  port: 8080

spring:
  # 关闭logo
  main:
    banner-mode: off
  # 激活文件
  profiles:
    active: mysql

# 日志配置
logging:
  level:
    com.workstation: debug
    org.springframework: warn

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.workstation
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类

# 项目相关配置
system:
  # 名称
  name: WorkStation
  # 版本
  version: 0.0.1
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math
  # 文件存储类型 local本地 minio 服务器
  fileType: local
  # 文件路径
  filePath: D:/workstation/uploadPath

mybatis-plus:
  global-config:
    db-config:
      # 主键ID类型
      id-type: none
      # 逻辑删除字段名称
      logic-delete-field: deleted
      # 逻辑删除-删除值
      logic-delete-value: 1
      # 逻辑删除-未删除值
      logic-not-delete-value: 0
    banner: off
  mapper-locations: classpath*:mapper/**/*.xml
# 认证配置
jwt:
  # 签署密钥
  secret-key: SecretKey012345678901234567890123456789012345678901234567890123456789
  # token 过期时间(单位:秒)
  expiration: 7200
task:
  pool:
    # 核心线程池大小
    core-pool-size: 10
    # 最大线程数
    max-pool-size: 30
    # 活跃时间
    keep-alive-seconds: 60
    # 队列容量
    queue-capacity: 10000