spring:
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/workstation
    username: root
    password: root@123
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password: redis@123
      timeout: 10s